### ISSUE TITLE
Isolate email_validation logic

### ISSUE THREAD

**Issue by alejandrodob** [PyBossa/pybossa#1014]
Make all the email_validation for both new user accounts and periodic validations (for newsletter purposes) be an option for each PyBossa server. Thus, an option in the settings file like the current ACCOUNT_CONFIRMATION_DISABLED, (or maybe this setting itself) should exist.

All the logic related to this should be isolated (including validation on account creation and update, permissions to contribute to projects with a non validated account, etc).

**Comment by teleyinex** [comment]
This is solved, right @alejandrodob ?

**Comment by alejandrodob** [comment]
first part is, but not the second (and most important one IMHO).

**Comment by alejandrodob** [comment]
This will be partially addressed by #1048. I will close it when this is merged.

**Comment by teleyinex** [comment]
This can be closed, right? Issue #1048 is solved already.

**Comment by alejandrodob** [comment]
Yes. I'm closing it.
