### ISSUE TITLE
Markdown does not render properly bullet lists *, -

### ISSUE THREAD

**Issue by teleyinex** [PyBossa/pybossa#1018]

**Comment by alejandrodob** [comment]
It's actually supported. The HTML for the lists is being generated: 
![screen shot 2015-02-12 at 12 43 52](https://cloud.githubusercontent.com/assets/5711098/6166888/10b9de54-b2b5-11e4-8412-4c3a2177c778.png)

Also this is correctly displayed as a list when using the default theme, but not on the CC one. So I'm guessing this is related to the custom CSS rules used on that last one.

I will move this issue to the CC theme.
