### ISSUE TITLE
Task and taskrun sometimes return empty files

### ISSUE THREAD

**Issue by therealmarv** [PyBossa/pybossa#1046]
task and taskrun files return sometimes empty files.

This problem can also be pyrax related.

This should be error prove in all circumstances.

**Comment by therealmarv** [comment]
Example URL: http://crowdcrafting.org/project/feynmanflowers/tasks/ export click

**Comment by alejandrodob** [comment]
As we discussed, this was related to user container visibility on Rackspace. One the containers were set back to public, the issue was solved, so I'm closing this.
