### ISSUE TITLE
Allow users to unsubscribe from newsletter

### ISSUE THREAD

**Issue by alejandrodob** [PyBossa/pybossa#1052]
Once a user has been subscribed to the newsletter, there's no way of unsubscribing from within PyBossa. Is this relevant? or should we delegate on the own newsletter email the user receives, which usually will contain an "unsubscribe" link at the bottom?

**Comment by teleyinex** [comment]
For the moment I wanted to keep it this way, otherwise we'll have to ensure synchronization everywhere. Users can un subscribe when they receive an email just following that link.

**Comment by alejandrodob** [comment]
Ok. Then closing it.
