### ISSUE TITLE
Support LDAP backend authentication

### ISSUE THREAD

**Issue by hijakk** [PyBossa/pybossa#1060]
I've already put some code together to do this in a one off, polishing it up and will submit a pull request to integrate this functionality sometime in the next few days.

Ultimately, I wanted to be able to use my existing infrastructure AD/LDAP as an authentication back end to allow users to log into PyBossa with their existing network accounts. This patch creates appropriate LDAP handlers in core.py, extensions.py, util.py and at view/account.py and introduces logic into the view.account.signin method where if all the LDAP configuration options exist in the settings_local.py file, the application will default to using LDAP as its authentication backend.

A small supplementary method at view.account.ldap_signup creates pybossa user objects when a user logs in for the first time.

This introduces a dependency on the simpleldap package.

**Comment by teleyinex** [comment]
See the PR for more information. It might be implemented as a PyBossa plugin.
