### ISSUE TITLE
email-verification: max. of 35 chars too restrictive

### ISSUE THREAD

**Issue by luddwichr** [PyBossa/pybossa#1064]
Setting the maximum number of characters to 35 for an E-Mail address field is too restrictive, in my opinion. I was not able to create an account with my normal e-mail-address on my local PyBossa instance and I don't see a reason why it should be limited so strictly. I'ld say 255 chars is a more realistic upper limit?
The issue refers to https://github.com/PyBossa/pybossa/blob/master/pybossa/forms/forms.py line 222 and subsequent code-segments. To make the code a bit more flexible, I'ld also suggest to set a constant value at the beginning of the file and refer to it, so changes only need to be done once.

**Comment by alejandrodob** [comment]
Hi @luddwichr, you are right. We are working on a fix for this issue.

Thanks
