### ISSUE TITLE
Improve documentation on how to deploy PyBossa as a service

### ISSUE THREAD

**Issue by luddwichr** [PyBossa/pybossa#1066]
When trying to deploy PyBossa as a service via Apache, i ran into several problems:

1. Error in documentation for how to create WSGI-Module: contrib/apache2/pybossa-site needs have file-extension '.config' to be handled correclty by Apache! (I cannot find the link again, but I read this on StackOverflow and this solved the issue that no WSGI-module was deployed)

2. An introduction on how to make RQWorker running in background after system up next to the webservice would be helpful. For me, after installing supervisor with `sudo apt-get install supervisor`, it worked by creating a file /etc/supervisor/conf.d/rq-worker.conf with the following content (replacing `<python-environment>` and `<user-name>` with the adequate values):
```
    [program:rq-worker]
    command=<python-environment> app_context_rqworker.py scheduled_jobs super high medium low quaterly monthly
    directory=/home/<user-name>/pybossa/
    autostart=true
    autorestart=true
    priority=997
    user=<user-name>
    log_stdout=true
    log_stderr=true
    logfile=/var/log/rq-worker.log
    logfile_maxbytes=10MB
    logfile_backups=2
```
and running `sudo /etc/init.d/supervisor restart` afterwards. Optionally I verified that the service is working using `sudo supervisorctl reload` and `sudo supervisorctl update`

3. running the WSGI-module with a root other than '/' specified by the line `WSGIScriptAlias / /home/user/pybossa/contrib/pybossa.wsgi` in /home/user/pybossa/contrib/pybossa.wsgi resulted in a whole stack of problems (e.g. for /pybossa instead of /). First, some hyper-links link back to '/' and hence I didn't land on the project main page but on by apaches default index.html. Secondly, e.g. the task presenter did not work properly anymore, since the api-calls are not using the new wsgi-path but still '/' and therefore result in an 404 error. Finally, I decided to switch back to the default '/'. However, always the apache default index.html page was shown if no other path than the root was specified. Thus, I added the option `DirectoryIndex disabled` to the directory descriptor in the pybossa.wsgi-file and it worked...

4. I am not much of a Linux expert, especially when it comes to properly setting up a secure way of user and group access rights. I think it would be helpful for many people to get a quick guide on how to set up users and groups and file-access permissions such that apache and postgres run savely without more access-rights than they need... However, of course this is not really your bussiness, but may be you have the knowledge and can put it into a few simple words ;-)

**Comment by therealmarv** [comment]
I'm updating this currently. But one information regarding this: We will not support Apache anymore for a production system (although it will work but no support from us). The only production server we will support is Nginx+UWSGI. Updates follow soon...

**Comment by therealmarv** [comment]
Everything updated with right templates for nginx, uwsgi & supervisor.

@luddwichr please check the docs at
http://docs.pybossa.com/en/latest/installing_pybossa.html
http://docs.pybossa.com/en/latest/nginx.html
