### ISSUE TITLE
Bootstrap-Design in Task Presenter Preview?

### ISSUE THREAD

**Issue by luddwichr** [PyBossa/pybossa#1067]
Is it possible to include the bootstrap design already when previewing the task presenter? This would make the development of new task presenters much more convenient, since the actual design could be checked.

**Comment by alejandrodob** [comment]
You are right, currently the preview is not as useful as it should. We will work on a solution for this, thanks!

**Comment by alejandrodob** [comment]
Closing as it has been fixed by https://github.com/PyBossa/pybossa-default-theme/commit/351a34437385858fcd16672908f8ae425c1da8cb
