### ISSUE TITLE
pybossa as a crowd-sensing platform

### ISSUE THREAD

**Issue by jruizaranguren** [PyBossa/pybossa#1088]
I have a particular use case of crowd-sourcing which aims at retrieving events / alerts from citizens related to environmental issues.

If I'm right pybossa is designed to build "static target" projects and divide them in micro-tasks. In my case, I have a never-ending project and each event would be handled independently.

Do you know if pybossa has been used for a crowd-sensing scenario? Or you can confirm me that it is not the right tool for that purpose.

Thanks

**Comment by alejandrodob** [comment]
Hello @jruizaranguren 

PyBossa has a module called autoimporters that runs as a regular background job and handles the import of new tasks from a given source to your project. So, suppose you have the volunteers generating by some means data that goes into a Google spreadsheet. This data will grow as the users contribute to it by retrieving this events/alerts you mention. The autoimporter will regularly check for new tasks in this spreadsheet and include them as new project tasks.

It might also be useful to you to use [Epicollect](http://plus.epicollect.net/), which allows the volunteers to collect data with their mobile devices. It is also integrated with PyBossa with the Epicollect importer, which, combined with the autoimporter, could work for your problem nicely.

Cheers

**Comment by alejandrodob** [comment]
I will close this, as this is not really an issue but a question.
