### ISSUE TITLE
Error installing pybossa server: Could not find a version that satisfies the requirement alembic

### ISSUE THREAD

**Issue by dc1520** [PyBossa/pybossa#1111]
I am installing pybossa server on redhat linux using virtualenv steps and following the installation steps from http://pybossa.readthedocs.org/en/latest/install.html. Getting following error,

Could not find a version that satisfies the requirement alembic<1.0,>=0.6.4 (from pybossa==0.2.2->-r requirements.txt (line 4)) (from versions: ) No matching distribution found for alembic<1.0,>=0.6.4 (from pybossa==0.2.2->-r requirements.txt (line 4))

Please help fixing this issue.

**Comment by therealmarv** [comment]
Hi!
Did you upgraded pip with `pip install -U pip` ?

I've checked PyBossa installation just now with a fresh Ubuntu VM and Alembic 0.7.6 is downloadable from PyPi: https://pypi.python.org/simple/alembic/

Please try to reinstall. Maybe you show your console output?

**Comment by dc1520** [comment]
I upgraded pip as mentioned. I recreated the virtualenv and the issue was resolved. Thanks for the reply.
