### ISSUE TITLE
Pybossa Server configuration for SSO

### ISSUE THREAD

**Issue by dc1520** [PyBossa/pybossa#1125]
How can a pybossa server be configured so that users logged into some application through web browser can also seamlessly login (Single Sign On) to pybossa server with SAML so that all authentication and authorization takes place centrally at a single identity provider?

**Comment by teleyinex** [comment]
Hi,

We're using Flask-Login, and as far as I know it does not provide SAML. However, PyBossa now features a plugin system, so you can extend it without problems to support your SAML requirements. Check the [documentation here](http://docs.pybossa.com/en/latest/plugins.html?highlight=plugin).
