### ISSUE TITLE
Can't clone submodule sphinx-theme-okfn

### ISSUE THREAD

**Issue by barens** [PyBossa/pybossa#1131]
The install juju charm fails when trying to clone pybossa because it can't get the theme.

Relevant log section:
> 2015-06-26 20:26:44 INFO install Submodule 'doc/_themes/sphinx-theme-okfn' (git://github.com/okfn/sphinx-theme-okfn.git) registered for path 'doc/_themes/sphinx-theme-okfn'
> 2015-06-26 20:26:44 INFO install Submodule 'doc/_themes/sphinx-theme-pybossa' (git://github.com/PyBossa/sphinx-theme-pybossa.git) registered for path 'doc/_themes/sphinx-theme-pybossa'
> 2015-06-26 20:26:44 INFO install Submodule 'pybossa/themes/default' (git://github.com/PyBossa/pybossa-default-theme) registered for path 'pybossa/themes/default'
> 2015-06-26 20:26:44 INFO install Cloning into 'doc/_themes/sphinx-theme-okfn'...
> 2015-06-26 20:27:22 INFO install fatal: Could not read from remote repository.
> 2015-06-26 20:27:22 INFO install
> 2015-06-26 20:27:22 INFO install Please make sure you have the correct access rights
> 2015-06-26 20:27:22 INFO install and the repository exists.
> 2015-06-26 20:27:22 INFO install Clone of 'git://github.com/okfn/sphinx-theme-okfn.git' into submodule path 'doc/_themes/sphinx-theme-okfn' failed

Attempting to clone the theme by itself also fails.
> git clone git://github.com/okfn/sphinx-theme-okfn.git
> Cloning into 'sphinx-theme-okfn'...
> fatal: read error: Operation timed out

**Comment by teleyinex** [comment]
@therealmarv can you check this issue. I've tried to clone by hand the repository and it works without problems. Maybe we should change it to http instead of git protocol.

**Comment by therealmarv** [comment]
yes this is the main problem here. Sometimes ssh/git is or other port than 80 & 443 blocked to go outside ! Looking into code to fix it.

**Comment by barens** [comment]
It's a problem I haven't come across before - the command fails with the git:// prefix, but works fine with http://

**Comment by therealmarv** [comment]
@barens this is now fixed. Please try again with a fresh install.

**Comment by barens** [comment]
Works great - thanks!
