### ISSUE TITLE
Alembic migration to version ac115763654 failed

### ISSUE THREAD

**Issue by alexandermendes** [PyBossa/pybossa#1140]
Hi,

I'm trying to pull the latest upgrades and when I reach the stage of upgrading the database structure I'm seeing the following error message.

ERROR [alembic.util] Online migration expected to match one row when updating 'aee7291c81' to 'ac115763654' in 'alembic_version'; 3 found

This might not be a PyBossa specific issue but perhaps you have an idea what could be causing this.

Thanks.

**Comment by alejandrodob** [comment]
Hi,

Do you use PostgreSQL version 9.3 or above?

Also, can you please paste here the output for ```alembic history```?

**Comment by alexandermendes** [comment]
Yep, I'm running PostgreSQL version 9.3.7.

Here's the `alembic history` output:

> ac115763654 -> 151b2f642877 (head), text to JSON
aee7291c81 -> ac115763654, remove_completed_column_from_project
4e435ff8ba74 -> aee7291c81, Rename app table to project
bbba2255e00 -> 4e435ff8ba74, Add subscribe column to user table
38a8a6299086 -> bbba2255e00, add email validation column
f8bc21a0be7 -> 38a8a6299086, Add newsletter columns
188c85878d36 -> f8bc21a0be7, Add audit log table
a9ecd1c767 -> 188c85878d36, add webhook column
66594a9866c -> a9ecd1c767, add pro field to user table
29353a1877ba -> 66594a9866c, add updated and state to app
537db2979434 -> 29353a1877ba, Remove featured table
7927d63d556 -> 537db2979434, Add category constraint to app/project
1eb5febf4842 -> 7927d63d556, n_answers migration
3da51a88205a -> 1eb5febf4842, Create blogpost table
46c3f68e950a -> 3da51a88205a, ckan api key constraint
4ad4fddc76f8 -> 46c3f68e950a, add table constraints to user locale and privacy mode
3620d7cac37b -> 4ad4fddc76f8, add privacy mode to user
3f113ca6c186 -> 3620d7cac37b, table_constrains
47dd43c1491 -> 3f113ca6c186, add app category field
27bf0aefa49d -> 47dd43c1491, create category table
9f0b1e842d8 -> 27bf0aefa49d, add colum ckan_api key field to user
50a846b021ae -> 9f0b1e842d8, add locale to user table
2a9a0ccb45fc -> 50a846b021ae, Add a column to App for user access control
4f04ded45835 -> 2a9a0ccb45fc, add google user id
3ee23961633 -> 4f04ded45835, Change long_description to UnicodeText
25e478de8a63 -> 3ee23961633, n_answers into task
51d3131cf450 -> 25e478de8a63, big int for oauth id
9341dfd1b21 -> 51d3131cf450, add featured table
a0d7c1872e -> 9341dfd1b21, admin field for users
35242069df8c -> a0d7c1872e, add facebook user id
2fb54e27efed -> 35242069df8c, app long description field
<base> -> 2fb54e27efed, Add twitter_user_id to the Column:User

**Comment by alejandrodob** [comment]
Hi again,

it seems something is wrong. I'm sorry but I would need a more direct feedback from you as I have no clue of what can be happening? Would you mind joining to our [slack channel](http://slackin.crowdcrafting.org/) so I can talk to you and help you better?

**Comment by alexandermendes** [comment]
It's ok actually, I've just managed to fix it, although it was a strange one. The table alembic_version had somehow ended up with three duplicate rows, so

```
pybossa=> select * from alembic_version;
```

returned

```

 version_num
-------------
 aee7291c81
 aee7291c81
 aee7291c81
(3 rows)
```

Removing those duplicate rows allowed me to run the migration succesfully. No idea how this happened but all sorted now anyway. Thanks!

**Comment by alejandrodob** [comment]
Great. In fact I tried to add some extra rows to alembic_version to try to reproduce your issue, but I was adding different values and the error was being different, and it seems that alembic was duplicating the same value! Good to know :).

Thanks!
