### ISSUE TITLE
Setting calibration / golden task / known answers / block low calibration users

### ISSUE THREAD

**Issue by dc1520** [PyBossa/pybossa#1144]
I want to setup pybossa project with certain tasks as golden one for which answers are known beforehand and they can be used to calibrate users. Few queries on this,
1. Are there any additional configuration required in addition to the tasks with a field named "calibration"? http://pybossa.readthedocs.org/en/latest/user/overview.html?highlight=calibrate
2. Is setting calibration value based on user's response, implicitly provided by pybossa server if tasks has the field named "calibration"? Or, this is to be done through custom program similar to code inside task presenter? 
3. What could be the reporting mechanism with which we can pull out the report from pybossa that details the calibration scale of the contributors?
4. How can I reject/block users to contribute who did not met the expectations answering golden questions?

**Comment by alejandrodob** [comment]
Hi @dc1520,

Basically, the calibration flag is just that, a flag, and it is not handled in any way inside the PyBossa server, so everything that you need to do with it must be manually handled by you. In particular, and responding to your 4 questions:

1. No, if the only thing you want to do is mark some tasks as golden. Then just import them with an specific value for calibration that you know marks them as golden tasks.
2. You would need to handle it yourself inside the task presenter Javascript, yes.
3. Again, you need to handle it manually.
4. You cannot do that, I'm sorry.

**Comment by dc1520** [comment]
Thanks for the confirmation
