### ISSUE TITLE
How to obtain list of projects in an html

### ISSUE THREAD

**Issue by dc1520** [PyBossa/pybossa#1146]
I want to add a new export option on ../themes/default/templates/admin/index.html admin page. Once admin chooses the project from drop down and hit Export button, all the completed tasks under that project will be exported into a persistent file. 

I have written python script that loads completed tasks based on my selection criteria from underlying database and is called upon hitting Export button, but I need to pass the project details to this python script as input. I looked at /project/_helper.html, but could not find any function that just returns me the list of projects. How do I get list of projects in an html? 

Any suggestion or code sample snippet will help. Thanks in advance.

**Comment by dc1520** [comment]
Is the project details stored in cache that can be fetched quickly in index.html? Or, can we write script that will call database once and fetch short_name from project table? Any sample code will help

**Comment by teleyinex** [comment]
Hi,

I don't fully understand what you want to do. Would you mind to give us more details?

In the meantime: for getting a list of projects from outside PyBossa I would recommend using the API. You can get a list of your projects in your PyBossa server just by browsing your API:

http://server/api/project

That will return 20 projects, and you can get the next 20 or more (limit is 100) passing the last ID of the project that you have received (see the [documentation](http://docs.pybossa.com/en/latest/api.html)).

For getting the completed tasks, PyBossa already runs a background job that exports to a ZIP file in two formats (CSV and JSON) the project tasks and task runs. Those two files can be accessed directly from the PyBossa project page. Is this not exactly what you want to build?

Cheers

**Comment by alejandrodob** [comment]
```
from pybossa.core import project_repo

all_projects = project_repo.get_all()
```
That will give you access to a list of every project on the database (both with tasks and without them).

Alternatively, you can get them from the cache module and take advantage of the caching, but it will be a few more lines of code:
```
from pybossa.cache import projects, categories

all_categories = categories.get_all()
all_projects = []
for category in categories:
    all_projects += projects.get_all(category)
```
That will give you the list of all projects that have tasks and a task presenter.

Also, as @teleyinex has pointed out, you can use the exporter module that will handle the creation of the files with tasks and taskruns in both CSV and JSON formats.

Best

**Comment by dc1520** [comment]
Thanks @teleyinex and @alejandrodob for your suggestions. My requirement is to handpick the fields from the tasks and include them in the completed tasks exported .json/.csv file which is not the case with current export framework of pybossa, Hence, I want to implement a customized export functionality. 
I would like to know the right approach to write code inside html file ( and not .py file), index.html in my case, to obtain the list of projects. I looked at existing htmls and did not found anything similar. I hope I am not missing something?

**Comment by alejandrodob** [comment]
Hi,

So the problem here is that, inside the html templates, you can only use the data that you pass them in the Flask view functions (plus some global ones that are available in all the templates). So, for example, [here](https://github.com/PyBossa/pybossa/blob/master/pybossa/view/admin.py#L85) you can see how we pass the projects to the /admin/projects.html template. So maybe you can build your exporter in that template too, using this projects variable.

I hope this helps.

**Comment by dc1520** [comment]
@alejandrodob , I managed to get the projects info available in html as you've suggested. Thank you very much
