### ISSUE TITLE
Pass local parameter from <script> to html through url_for() ?

### ISSUE THREAD

**Issue by dc1520** [PyBossa/pybossa#1148]
This is more of html jinja question than pybossa question in general. I have limited knowledge about jinja. Hence, I thought to share with pybossa gurus so that with their experience, I may get some useful info to fix my problem

I have modified ../themes/default/template/admin/index.html to include
Drop down: listing all the projects created named : "project-list"
Clickable button: "_JSON" . On click will export the completed tasks for the project selected in drop down control

There are examples of how to use global variable inside url_for() such as usage of project.draft or c.short_name in index.html. But in my use case, the difference is the variable is created inside index.html. And it didn't work that way. Here is the code snippet for reference

{% block content %}
var x

<script>
var urlPath;
function projHandler() {
	x = document.getElementById("project-list").value;
}
</script>

<div class="row">
…
		<div class="row-fluid">
            <div id="cust-exp-json" class="span6 well">
                <h2><i class="icon-user"></i> {{_('Export Tasks')}}</h2>
                <p>{{_('Customized export of completed tasks')}}</p>				
				<select id="project-list" onchange="projHandler()">
				{% for c in categories %}
					{% for project in projects[c.short_name] %}
						<option value = {{project.id}}> {{ project.name }}</option>
					{% endfor %}
				{% endfor %}
				</select>
				<a href="{{url_for('admin.custom_export_tasks', id=x)}}" class="btn btn-primary">
                    {{ _('JSON') }} <i class="icon-chevron-right"></i>
                </a>
            </div>
</div>

  File "..../pybossa/pybossa/themes/default/templates/admin/index.html", line 96, in block "content"
    <a href="{{url_for('admin.custom_export_tasks', id=x)}}" class="btn btn-primary">
  File ".../pybossa/env/local/lib/python2.7/site-packages/flask/helpers.py", line 305, in url_for
    force_external=external)
  File ".../pybossa/env/local/lib/python2.7/site-packages/werkzeug/routing.py", line 951, in to_url
    value = self.num_convert(value)
UndefinedError: 'x' is undefined
{% endblock %}

**Comment by teleyinex** [comment]
Hi,

To set a variable in Jinja you've to write the following:

  {% set foo = 42 %}

You can find more info [here](http://jinja.pocoo.org/docs/dev/templates/#with-statement). I hope this helps ;-)
