### ISSUE TITLE
Force cache update

### ISSUE THREAD

**Issue by analizoInfo** [PyBossa/pybossa#1193]
Hi, is there any way to force projects percentage update?

After a successful pybossa migration it seems not showing all the statistics, percentages, users, tasks as should be.

Example:

http://analizo.info/project/per-lhorta-sud-2014/
http://analizo.info/project/per-lhorta-sud-2014/tasks/browse

http://analizo.info/project/per-lhorta-nord-2014/

http://analizo.info/project/per-lhorta-nord-2014/tasks/browse

Thanks.

**Comment by alejandrodob** [comment]
Hi,

You can either disable the global cache, by setting an environment variable, as explained [here](http://docs.pybossa.com/en/latest/customizing.html?highlight=cache#disabling-the-cache), or modify the specific cache timeout values to some lower values (or even to zero) in your settings_local.py file. That is also explained [here](http://docs.pybossa.com/en/latest/customizing.html?highlight=cache#cache).

Of course, more fine customisations can be made, but they'd maybe imply modifications in the PyBossa code itself (creating new cache constants, using them where you require and add them to the settings_local.py file, for instance).

I hope this helps. If you have any other question please ask!

**Comment by analizoInfo** [comment]
So the trick was:

1) Adding "PYBOSSA_REDIS_CACHE_DISABLED" to the ".bashrc"

vim .bashrc

export PYBOSSA_REDIS_CACHE_DISABLED='1'

. .bashrc

2) Check if it works:

python

import os

os.environ.get('PYBOSSA_REDIS_CACHE_DISABLED')

Ctrl + D

3) And change the "Task Redundancy" from projects to another value to force the update.

Thanks @alejandrodob !
