### ISSUE TITLE
Quarterly emails do not work

### ISSUE THREAD

**Issue by alejandrodob** [PyBossa/pybossa#1206]
It seems that the emails sent to users telling about their inactivity on the platform are not working correctly, as some of them are being sent to users which have had some kind of recent activity.

**Comment by teleyinex** [comment]
Yes, the query is wrong. This should be used instead:

```sql
select user_id from task_run where user_id is not null and user_id not in (select user_id from task_run where user_id is not null and to_date(task_run.finish_time, 'YYYY-MM-DD\THH24:MI:SS.US') >= NOW() - '3 month'::interval group by task_run.user_id order by user_id) group by user_id order by user_id;
```

**Comment by teleyinex** [comment]
This query improves the previous one taking into account only inactive users in the last 3 months, but that have participated in the last year:

select user_id from task_run where user_id is not null and user_id not in (select user_id from task_run where user_id is not null and to_date(task_run.finish_time, 'YYYY-MM-DD\THH24:MI:SS.US') >= NOW() - '3 month'::interval group by task_run.user_id order by user_id) and to_date(task_run.finish_time, 'YYYY-MM-DD\THH24:MI:SS.US') >= NOW() - '1 year'::interval group by user_id order by user_id;

Users that have participated more than 1 year ago, will not be interested in coming back. I guess :D
