### ISSUE TITLE
sqlalchemy compile Error on ubuntu-14.04

### ISSUE THREAD

**Issue by mrudulachougule** [PyBossa/pybossa#1217]
Hi,

I am trying to create data base which takes value from panel which is being build in  glade using gtk tool. When i'm trying to run my application which creates data base for front end. I'm getting below error;
"sqlalchemy.exc.compileError:Unconsumed Column name: column name"

Please share your views / ideas to solve this error.

Thanks

**Comment by teleyinex** [comment]
Hi,
We don't use glade or GTK to run PyBossa, so I don't know how this is related to PyBossa. Would you mind to explain a bit more what you are trying to achieve?

All the best,

Daniel

**Comment by mrudulachougule** [comment]
Hi Daniel,

I am porting my python application from Ubuntu 10.04 to 14.04. My python
has detabase and C coding in the back-end and front end screens / panels
are designed in gtk-glade when i'm trying to run my application. I am
getting below error:
sqlalchemy compile Error on ubuntu-14.04

Please share your views to resolve this issue



Thanks,

Mrudula

**Comment by teleyinex** [comment]
But are you using PyBossa? Because it looks like you are having an issue with SQLAlchemy and we are not the developers.

**Comment by mrudulachougule** [comment]
Alright. Thanks.

**Comment by alejandrodob** [comment]
Closing this as it seems not related to PyBossa.
