### ISSUE TITLE
Vagrant box URL returning 404

### ISSUE THREAD

**Issue by alejandrodob** [PyBossa/pybossa#1218]
![screenshot from 2015-11-10 18 55 03](https://cloud.githubusercontent.com/assets/5711098/11070580/ad3ee736-87dc-11e5-8e17-952fa703ea58.png)

cc/ @therealmarv

**Comment by alejandrodob** [comment]
I've just tried again and it is working now. So I'm closing this.

**Comment by therealmarv** [comment]
Yes strange, I've also tested this yesterday evening. Everything was fine. So Ubuntu servers were down ;)
