### ISSUE TITLE
Handling multibyte characters in pybossa

### ISSUE THREAD

**Issue by dc1520** [PyBossa/pybossa#1251]
I want to get non english characters response from crowd; multi byte character set such as traditional/simplified chinese. Are there any settings that I need to apply into the task presenter code so that the task_run response json contains correct chinese characters and not the utf-8 code associated with the characters?

**Comment by alejandrodob** [comment]
The json response that is sent to the server contains the actual chinese characters. You can see that by inspecting the network request made via AJAX from the presenter, when saving an answer (in the Chrome devtools, select the network tab and check the POST to /taskrun. Then inspect the content of the request and you will see it).

However, I guess that you are having this issue for some reason and I would like to know why, so could you please tell me where are you getting your data that is not in the chinese characters but in the utf8 codes?

**Comment by dc1520** [comment]
Thanks @alejandrodob
