### ISSUE TITLE
User confirmation email

### ISSUE THREAD

**Issue by mtorrisi** [PyBossa/pybossa#1268]
Hello to everyone,

I'm installing a new Pybossa server in my department, but I'm facing  a strange issue. 
I've enabled the confirmation email in settings_local.py file as follow
```
...
ACCOUNT_CONFIRMATION_DISABLED = False
...
```
but no mails is sent on a new user registration, even if the mail server is correctly configured. I configured postfix in the same Pybossa host and I receive the mails in case of errors since I enabled the ADMINS list in the settings file.

Any suggestion?

Thanks in advance

**Comment by therealmarv** [comment]
thanks for reporting @mtorrisi 

I will setup a new pybossa on my machine with postfix and will try to reproduce the problem.

Just to confirm you've set the settings here right? https://github.com/PyBossa/pybossa/blob/master/settings_local.py.tmpl#L86

**Comment by mtorrisi** [comment]
mmm... I didn't change those line, since currently postfix doesn't need authentication.
```
## Mail setup
MAIL_SERVER = 'localhost'
MAIL_USERNAME = None
MAIL_PASSWORD = None
MAIL_PORT = 25
MAIL_FAIL_SILENTLY = False
MAIL_DEFAULT_SENDER = 'DFA Projects Support <my-mail@my-domain.com>'
```

**Comment by mtorrisi** [comment]
Hi @therealmarv 

I think that problem was related to the worker
```
python app_context_rqworker.py scheduled_jobs super high medium low
```
When I restarted the server all the mails queued has been sent normally and the new registration request receive the confirmation. I think that we can close here the issue.

Thanks a lot.

**Comment by therealmarv** [comment]
oh thanks. What a relief. I wanted to set up a local mailserver right now :)

Yes the scheduler is important and should run a service in background all the time. It handles all the queue stuff like ZIP creation and mail sending also (did not thought about it yesterday).

But I will definitely change & add to the docs to highlight this behaviour with rq.

Thanks for your feedback! I will close this issue.
