### ISSUE TITLE
Translating PyBossa

### ISSUE THREAD

**Issue by mtorrisi** [PyBossa/pybossa#1271]
Hi all,

I think that something is missing in the doc. What I mean is, [this](http://docs.pybossa.com/en/latest/translating.html#adding-a-new-language) section state: 

> Once you have translated all the strings, all you have to do is compile the translation with this command:

But there is any command below. What is the command that I have to perform?

Thanks

**Comment by therealmarv** [comment]
hi @mtorrisi, thanks for reporting. This is actually an error in our docs. I've fixed that (I will publish soon) and in the meantime look here for the full documentation:

https://github.com/PyBossa/pybossa/blob/f9fbd746d9f9697eb99a7e9ddd3940d593726b75/doc/translating.rst#adding-a-new-language

THANKS!
