### ISSUE TITLE
Question on USER_TIMEOUT

### ISSUE THREAD

**Issue by dc1520** [PyBossa/pybossa#1281]
The Pybossa documentation about USER_TIMEOUT says,
PyBossa comes with a default set of timeouts for different views that you can change or modify to your own taste. All you have to do is modify the following variables in your settings file:
USER_TIMEOUT = 15 * 60
Every value is in seconds, so bear in mind to multiply it by 60 in order to have minutes in the configuration values.

Question:
1. This settings are to be applied in settings_local.py?
2. If USER_TIMEOUT is not set, the default is unlimited timeout?
3. Is this the only setting to be done if user session is supposed to be timed out after 15 mins(as per above settings) of inactivity? Any settings to be applied on REDIS server separately?

**Comment by teleyinex** [comment]
Hi,

Here you've the answers:

1.- Yes, it should be placed in settings_local.py
2.- No, there's a default time out: https://github.com/PyBossa/pybossa/blob/master/pybossa/default_settings.py#L67
3.- This is not for the sessions, this is for the REDIS cached views.
