### ISSUE TITLE
Change the administrator

### ISSUE THREAD

**Issue by jimy811111** [PyBossa/pybossa#1304]
Hi, I just install a PyBossa server on my AWS. Unfortunately, I use the wrong information to register the first user and forget these information. Thus, I cannot manage users' account. Is there any method to modify this mistake? Thanks!

**Comment by therealmarv** [comment]
For password there should be a forgot password link. If you want to make another user an admin you can do so by directly connecting to the Postgres database and enable the admin field in the public.user table.

**Comment by jimy811111** [comment]
That solved my problem. Accessing the Postgres database is what I really need to do, thanks!
