### ISSUE TITLE
Some questions about customized my PyBossa server

### ISSUE THREAD

**Issue by jimy811111** [PyBossa/pybossa#1307]
Hello, I install PyBossa on AWS and try to customize it .There are some questions which bother me and I can not find the solution. 
1. I want to know every user's contribution in a project. Is this information recorded in my database?
2. After viewing the relations in database, I am wondering is my project presenter recorded in the database or I can find a html file in some place recoding the presenter.
3. I want add some input in sign-up page(e.g. address) for rewarding but I cannot find where is the html content produced and which code make it save to database.
Thank you for reading that much questions.

**Comment by teleyinex** [comment]
Hi,

I'll answer them here:

1.- Yes, it's. You can use the endpoint userprogress to get that information. Check the Flickr template, as it has code about how you can do it.

2.- Yes, it's recorded in the database. We use JSON store type, to have everything in the info field of the project. If you use SQL JSON queries, you can get the template info. Check PostgreSQL documentation about how to query JSON information.

3.- For modifying the user table, you will need to add a migration to the server. Check the models and extend the user one. Then, go to the views, and check for the forms file. Extend to reflect the changes (i.e. the address). Then, go to the themes, and be sure that your theme reflects those changes (if you are using the macro for forms, it should be shown out of the box).

All the best,

Daniel
