### ISSUE TITLE
Issues with manual installation instructions

### ISSUE THREAD

**Issue by vitorbaptista** [PyBossa/pybossa#1309]
I walked through the PyBossa install instructions on http://docs.pybossa.com/en/latest/install.html and had a couple problems might be useful to share.

First, it complained on not having the `oauthlib` package installed, which was odd considering it is a dependency of `Flask-OAuthlib`. I had to then manually `pip install oauthlib`. I couldn't debug further.

After that was fixed, it started complaining that it couldn't find any templates (TemplateNotFound). After reading your `.travis.yml`, I realized that was because I haven't ran `git submodule update --init --recursive`. It would be good to add this to the instructions

After these changes, the only tests that fail locally are:

```
======================================================================
1) FAIL: Test i18n anonymous works
----------------------------------------------------------------------
   Traceback (most recent call last):
    env/lib/python2.7/site-packages/nose/case.py line 197 in runTest
      self.test(*self.arg)
    test/test_i18n.py line 49 in test_00_i18n_anonymous
      assert "Comunidad" in res.data, err_msg
   AssertionError: The page should be in Spanish
======================================================================
2) FAIL: Test i18n as an authenticated user works
----------------------------------------------------------------------
   Traceback (most recent call last):
    env/lib/python2.7/site-packages/nose/case.py line 197 in runTest
      self.test(*self.arg)
    test/test_i18n.py line 71 in test_01_i18n_authenticated
      assert "Comunidad" in res.data, err_msg
   AssertionError: The page should be in Spanish
```

I haven't debugged those, as they seem minor.

**Comment by teleyinex** [comment]
Hi, thanks for the heads up. It looks like you didn't clone the repository with the --recursive option, can you confirm if you did it?

**Comment by vitorbaptista** [comment]
*facepalm*

No, I didn't. That was it for the templates, sorry for the wrong report.

**Comment by teleyinex** [comment]
No worries. Closing it!
