### ISSUE TITLE
Is it possible to add tasks in bulk via the API?

### ISSUE THREAD

**Issue by vitorbaptista** [PyBossa/pybossa#1314]
_Sorry if this isn't the correct medium to ask these type of questions. If not, please point me to the correct one._

I'm creating a project that'll have a large amount of tasks, which will take a long time to create one by one (specially given the rate limitation). Is there a way to push a CSV or some other file type with the tasks to be created via the API, or the web UI is currently the only option?

**Comment by teleyinex** [comment]
Hi,

No, we've not added such a feature right now. We should add it in the future, but right now it's not in our roadmap.

Cheers
