### ISSUE TITLE
SQlalchemy pbkdf2 hash error

### ISSUE THREAD

**Issue by Lythimus** [PyBossa/pybossa#1316]
I keep getting a generic "Ooops, Something's wrong" error when trying to load projects (project/category/featured/) or submitting a new project (project/new) on my local install running from the pybossa Vagrantfile (not the Juju Vagrantfile) using Postgres 9.3.

I've had a tremendous amount of trouble trying to keep Pybossa stable on my local machine via Vagrant and on a CentOS server by hand. So I would appreciate some insight as to what might be causing the following warning and the above general error:

`/home/vagrant/pybossa-env/local/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py:185: SAWarning: Unicode type received non-unicode bind param value 'pbkdf2:sha1:1000$Iv4UAiqW...'`

**Comment by teleyinex** [comment]
Hi,

We test all the code in Ubuntu machines, so I would think that it's a problem with the UNICODE config of CentOs. We cannot give you any advice on that specific issue, as it look like it's a problem with SQLAlchemy. 

Sorry.
