### ISSUE TITLE
Pybossa server version

### ISSUE THREAD

**Issue by dc1520** [PyBossa/pybossa#1320]
How do I find pybossa server version by making restful api call? Also, as of date the latest release/version of pybossa shows v2.3.0, whereas "pybossa/__init__.py" has version 1.5.1. Looking at the history of "pybossa/__init__.py", it seems until 1.5.1, the version and release tag were in sync. Is it the case that "pybossa/__init__.py" is to be updated to 2.3.0?

**Comment by teleyinex** [comment]
We're not exposing that info via the API, sorry. Do you mean by tags? The version is being kept in [setup.p](https://github.com/PyBossa/pybossa/blob/master/setup.py)

**Comment by dc1520** [comment]
@teleyinex , thanks for confirming about no interface to check pybossa server version and providing the right location https://github.com/PyBossa/pybossa/blob/master/setup.py to look at to get server version. And yes, by pybossa server version, i meant label/tag in repo. Should https://github.com/PyBossa/pybossa/blob/master/pybossa/__init__.py also be update to 2.3.0 in addition to  https://github.com/PyBossa/pybossa/blob/master/setup.py?
