### ISSUE TITLE
Add 'embedded' mode for apps

### ISSUE THREAD

**Issue by gka** [PyBossa/pybossa#315]
**Problem:** one cannot embed CrowdCrafting apps into external websites at the moment, for instance on news websites for amazing crowdsourcing ddj applications..

**Solution:** provide an 'embedded' mode that displays the task presenter without CrowdCrafting header & footer, maybe with a small crowdcrafting logo in the bottom.

Need to think about an easy way to login, though. Maybe we could have a small popup window opening per default if new users entering an app in embedded mode. The popup would ask them to login via Twitter/Facebook or do tasks anonymously. Would be nice if this would fit in something around 400px width.

Also we need to make sure that crowdcrafting.org is ready to take significant load, as news websites easily reach +100k visits per day.

**Comment by teleyinex** [comment]
we will not implement this for the moment.
