### ISSUE TITLE
no database config item should mean user gets explicit error

### ISSUE THREAD

**Issue by mk270** [PyBossa/pybossa#530]
If you don't have a database URI set up for SQLAlchemy, you get an error. These URI needs to come from the environment (for Heroku) or the config file.

Currently, we don't assert that this be present; this means an administrator can get a SQL failure from postgres (e.g., "no such table") and not realise this due to a failure to set the DB URI (as opposed to something wrong with alembic, etc).

We should make this condition *much* more obvious; otherwise developers can get confused, particularly given that they may need to switch between Heroku and non-Heroku branches, and given that the config.py file is gitignored.

**Comment by teleyinex** [comment]
Not relevant anymore as right now the complexity of PyBossa does not allow to run fully on Heroku as you need Sentinel and it's only enabled for high volume accounts.
