### ISSUE TITLE
M2Crypto cannot be installed on Heroku

### ISSUE THREAD

**Issue by FTraian** [PyBossa/pybossa#587]
While trying to install Pybossa on heroku it fails because of M2Crypto dependency. There are two steps to fix this issue:

1. In requirements.txt change dependency directly to github:
-e git+https://github.com/Hypernode/M2Crypto#egg=M2Crypto-0.22.dev

2. With this dependency SWIG compilation fails due to a wrong path. This can be fixed using a custom buildpack as described here:  http://stackoverflow.com/questions/10334920/heroku-buildpacks-installing-executables-that-are-used-by-python-packages
The Heroku deployment doc page needs to be updated accordingly

**Comment by teleyinex** [comment]
Yes, we don't support Heroku so we can close this issue.

**Comment by FTraian** [comment]
If you don't support Heroku then you should remove this page: http://docs.pybossa.com/en/latest/heroku_deploy.html?highlight=heroku

**Comment by teleyinex** [comment]
Thanks for the follow up. We forgot to remove that page. We'll do. @alejandrodob can you remove that page from the documentation?

**Comment by alejandrodob** [comment]
fixed.
