### ISSUE TITLE
Spanish translation incomplete

### ISSUE THREAD

**Issue by alejandrodob** [PyBossa/pybossa#661]
I've seen that the Spanish i18n (and I believe that the same applies to French) lacks some strings  properly translated. It can easily be seen if one extracts the messages.pot file with the command "pybabel extract -F babel.cfg -k lazy_gettext -o messages.pot translations/" which will create a translation template that is different (more complete) than the previous one. And when updating the existing translations with 
"pybabel update -i messages.pot -d es/", the new .po file created is not complete, so needs the gaps to be filled in with the proper translated phrases.

**Comment by teleyinex** [comment]
This is almost completed, right?

**Comment by alejandrodob** [comment]
No, what is completed is the wrapping of all the text in the templates with _() but the translation itself is far from being completed. We should maybe add a project to CC like the Italian one, what do you think?

**Comment by alejandrodob** [comment]
Addressed and solved as part of #1110
