### ISSUE TITLE
task.info clobbering task

### ISSUE THREAD

**Issue by redhog** [PyBossa/pybossa#671]
In several places in the code, data from task.info is loaded directly into task, along these lines:

for key, value in task.info.iteritems():
    setattr(task, key, value)

If info contains fields with names used internally by Task, like id, n_answers (or info!) things will break.

This is especially a problem if you load the results (task_run data) of one app as apps for another app, and don't clean the data properly in between.

One examle of where this happes is in the CSV exporter.

Suggested solution: Mangle names so that {"foo": {"bar": 1, "fie": {"baz": 2}}} becomes foo__bar=1, foo__fie__baz=2.

**Comment by teleyinex** [comment]
@alejandrodob did we solve this issue? If I remember this is something that we must look at it.

**Comment by alejandrodob** [comment]
No, we did not take any further steps, so last update on this was my last comment.

I can go back to it now and either fix this or close the issue. :+1:

**Comment by alejandrodob** [comment]
I've double-checked all the code and this is not happening anywhere, as we are already appending prefixes to the info attributes when exporting CSV files, so I'm closing this.
