### ISSUE TITLE
Hide application dependant resources if the app is hidden

### ISSUE THREAD

**Issue by alejandrodob** [PyBossa/pybossa#721]
The resources like tasks, task runs and future blogs which are part of an application should be non accessible if the app is marked as hidden by its owner, not only at the web navigation level, but more importantly at the authorisation one. So we need to modify the auth files to update the read functions and consider the fact that the app they belong to may be hidden. Modify the tests too, or add them if missing.

**Comment by teleyinex** [comment]
@alejandrodob can you update this issue with the latest status?

**Comment by alejandrodob** [comment]
This has not been addressed. Auth module has had updates but this behaviour has not been implemented.

**Comment by alejandrodob** [comment]
I'm closing this, because hidden projects were deprecated after #1176
