### ISSUE TITLE
Environment variable PYBOSSA_SETTINGS is ignored when settings_local.py existing.

### ISSUE THREAD

**Issue by therealmarv** [PyBossa/pybossa#724]
Don't know if this is a bug or feature but I spend some time/pain before I figured out why my configuration is not working:

When `settings_local.py` is existing the environment variable

    export PYBOSSA_SETTINGS={/my/config/file/somewhere}

will be ignored.

**Comment by teleyinex** [comment]
I think this is an issue. We should take a look at it, but I've never ever used the env variable. Should we keep this issue opened?

**Comment by therealmarv** [comment]
is not anymore the case. Will close that issue.
