### ISSUE TITLE
Renaming apps to projects for endpoints and API also

### ISSUE THREAD

**Issue by therealmarv** [PyBossa/pybossa#784]
This is the most complicated part of renaming to "projects" and therefore a seperate issue. See #531 for the overall problem.

Needs to be done:
* keep sure that old API keeps working
* introduce maybe a new API with version numbers (v1, v2, ...) on endpoints?!
* lots of internal changes for endpoints

**Comment by teleyinex** [comment]
Please follow the solution in this PR #1039
