### ISSUE TITLE
Add a descriptive URL to blog posts

### ISSUE THREAD

**Issue by alejandrodob** [PyBossa/pybossa#801]
Currently, the URL for a blogpost is of the form /app/<app_name>/blog/blogpost_id
It should be something like /app/<app_name>/this-is-the-title-of-a-post_id

In addition, when creating a new blogpost, it should show how the URL will look like (auto generated from the blogpost title).

**Comment by teleyinex** [comment]
This is being now discussed with Álvaro and Jorge, so closing it as it is not relevant for the moment.
