### ISSUE TITLE
PyBabel extract, update, compile instructions are missing

### ISSUE THREAD

**Issue by therealmarv** [PyBossa/pybossa#806]
This is missing in the docs.

* PyBabel commandline interface: http://babel.pocoo.org/docs/cmdline/
* Got a description on how to update PyBossa translation files for different languages here: https://github.com/PyBossa/pybossa/blob/master/doc/translating.rst
* But no description on how to extract initially. I used #661 for extracting, updating and compiling language files:

My approach to update most of the language files.
Go to pybossa directory where pybabel.cfg is inside
```
pybabel extract . -F babel.cfg -k lazy_gettext -o translations/messages.pot
pybabel update -i translations/messages.pot -d translations
pybabel compile -d translations
````

**Comment by teleyinex** [comment]
@therealmarv can you add the instructions to the docs so we can close this issue?
