### ISSUE TITLE
Apps to Projects renaming in translations files (Spanish and French) is not done yet.

### ISSUE THREAD

**Issue by therealmarv** [PyBossa/pybossa#807]
TO DO:
Translations files (Spanish and French) are not translated fully for renaming `apps` to `projects`.
Renaming will be done in #531 but this is a separate issue only for translation files.

Also see #806 

When looking at `.po` files look for especially for the word `fuzzy` which marks incomplete translations.

**Comment by teleyinex** [comment]
In Spanish it's done not in French, but none of our team members actually speak French so we can close this issue. PyBossa can specify in its config file which languages are supported, so French can be disabled.
