### ISSUE TITLE
Upgrade Google authentification to Google+ sign in

### ISSUE THREAD

**Issue by therealmarv** [PyBossa/pybossa#968]
Google OpenID is deprecated:
https://developers.google.com/accounts/docs/OpenID#shutdown-timetable

Google+ sign in is needed. Example from Polymer [here](http://googlewebcomponents.github.io/google-signin/components/google-signin/demo.html) on the second button (email only needed).

Tested and works: Google+ signin without having a Google+ Account.

**Comment by therealmarv** [comment]
We are not using Google OpenID. We are using OAuth2 OpenID Connect. OAuth2 scopes need update.

**Comment by teleyinex** [comment]
@therealmarv is this solved? I guess yes, so if the answer is yes, please close it.

**Comment by therealmarv** [comment]
yes, solved. Closing...
