### ISSUE TITLE
Setup PyBossa with HTTPS

### ISSUE THREAD

**Issue by abheritage** [PyBossa/pybossa#976]
Hi all,
I have been trying in vain to get PyBossa setup on Apache with HTTPS. I have all HTTP requests redirected to HTTPS. In my default-ssl.conf file, I have setup the certificates and every page I access from other areas of the site, things work. But PyBossa is giving me trouble. Here is the portion I have for PyBossa:

```
Header set Strict-Transport-Security "max-age=31536000; includeSubDomains"
WSGIDaemonProcess pybossa user=www-data group=www-data threads=5
WSGIScriptAlias /crowd /home/ubuntu/dev/pybossa/contrib/pybossa.wsgi
		
<Directory /home/ubuntu/dev/pybossa>
  WSGIProcessGroup pybossa
  WSGIApplicationGroup %{GLOBAL}
  Require all granted
  SSLOptions +StdEnvVars
</Directory>
```
As per [this page](http://www.pdxpixel.com/blog/setting-up-django-site-ssl-apache-mod_wsgi-mod_ssl/), I have also modified pybossa.wsgi by adding:
```
import os
os.environ['HTTPS'] = "on"
```
I added the following to settings_local.py
```
# secure proxy SSL header and secure cookies
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# session expire at browser close
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# wsgi scheme
os.environ['wsgi.url_scheme'] = 'https'
```
However, I keep getting 404 error.

While I was using the original pybossa-site.conf file that came with pybossa source, everything worked fine. However, I just can't get it to work within an environment where everything goes through SSL. 

Any guidance is greatly appreciated.

**Comment by teleyinex** [comment]
This issue is related to the web server employed and not the code itself. Closing it.
